### ISSUE TITLE
ExtendedTemporalMemory: dimension of apical and  basal input?

### ISSUE THREAD

**Issue by Thanh-Binh** [numenta/htmresearch-core#17]
@mrcslws last year i worked with your etm and found it has the same interface like tp or tm, but much better than TP or TM. In the mean time the dimension of basal and apical input is needed  for  initializing. I set them to zeros and got an error like segmentation fault. 
Could you plese recommend me the value of apical and basal input dimension so that it works without errors and at least like the old version?
Do you have any example for using the new etm?
Best thanks

**Comment by rhyolight** [comment]
Hi @Thanh-Binh! We appreciate your interest in our research, but keep in mind that [these conditions](https://github.com/numenta/htmresearch#what-you-should-understand-about-this-repository) also apply to this codebase.

**Comment by Thanh-Binh** [comment]
Matt: only a little understanding the compatibility to the old version, because i do not have the old version of etm.
